// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TestRunner")>]
[<assembly: AssemblyProductAttribute("Shed")>]
[<assembly: AssemblyCompanyAttribute("Enkomio")>]
[<assembly: AssemblyDescriptionAttribute("A .NET runtime inspector.")>]
[<assembly: AssemblyVersionAttribute("2.0.0")>]
[<assembly: AssemblyFileVersionAttribute("2.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("2.0.0.*")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TestRunner"
    let [<Literal>] AssemblyProduct = "Shed"
    let [<Literal>] AssemblyCompany = "Enkomio"
    let [<Literal>] AssemblyDescription = "A .NET runtime inspector."
    let [<Literal>] AssemblyVersion = "2.0.0"
    let [<Literal>] AssemblyFileVersion = "2.0.0"
    let [<Literal>] AssemblyInformationalVersion = "2.0.0.*"
