// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Shed")>]
[<assembly: AssemblyProductAttribute("Shed")>]
[<assembly: AssemblyCompanyAttribute("Enkomio")>]
[<assembly: AssemblyDescriptionAttribute("A .NET runtime inspector.")>]
[<assembly: AssemblyVersionAttribute("1.1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("1.1.0.*")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Shed"
    let [<Literal>] AssemblyProduct = "Shed"
    let [<Literal>] AssemblyCompany = "Enkomio"
    let [<Literal>] AssemblyDescription = "A .NET runtime inspector."
    let [<Literal>] AssemblyVersion = "1.1.0"
    let [<Literal>] AssemblyFileVersion = "1.1.0"
    let [<Literal>] AssemblyInformationalVersion = "1.1.0.*"
